Add GECOS field on UNIX systems.
rustadopt/uzers-rs pull request #13
Opened 2023-10-16 06:22 UTC by apognu

This pull request adds the comment field (GECOS) that should be present on UNIX systems to the `UserExtras` struct as an `Option<OsString>`. The field would be `None` if the field is empty.

Refers to #12.

2023-10-19 16:36 UTC, OLEGSHA commented
Hmm... Why is it a `Option`? How is an empty GECOS comment different from a missing GECOS comment? Why can `with_gecos` not be used to set the comment to `None`?

2023-10-20 08:36 UTC, apognu commented
Done. Should I add some tests around this? I could not find any tests related to `extras`, but I can add them if you want.

2023-10-20 11:02 UTC, OLEGSHA commented
There's a general lack of unit tests for the core functionality in the crate, and I think it'd be best to address this in a separate PR, For the sake of consistency I'd leave this PR as-is. I assume you've tested everything manually. Anyway, LGTM.

Erm... so I'm not really the maintainer, so you've got to wait for @gierens who seems to be running the place. Should take about a week from my experience.

2023-10-20 12:51 UTC, apognu commented
Noted.

Yes, I have tested manually from different NSS providers, and things were fine. :+1:  Could not test on BSD, though.

2023-10-25 17:45 UTC, gierens commented
Hey guys, sorry for the late reply, been a little busy lately.

Thanks for the contribution, this looks good to me. The only thing that also was mnetioned would be testing. Sure, @OLEGSHA you are correct, there is a lack of tests ... but we have to start somewhere, so it would be great if you could add tests for this @apognu

2023-10-25 17:45 UTC, gierens requested changes
Hey guys, sorry for the late reply, been a little busy lately.

Thanks for the contribution, this looks good to me. The only thing that also was mnetioned would be testing. Sure, @OLEGSHA you are correct, there is a lack of tests ... but we have to start somewhere, so it would be great if you could add tests for this @apognu

2023-10-25 17:48 UTC, apognu commented
Sure thing! I'll add a few by tomorrow and push again.

2023-10-25 18:17 UTC, apognu commented
I added a few (mocked) tests, and edited the debug print one.

We are in the same situation, unfortunately, as with the other cases where I cannot assume a user on the system, or the current user, will have a comment specified (or even verify it). So short of refactoring the tests to use something like `nss_wrapper`, or you see another way of testing for this, I do not know if I can do more.

2023-10-28 08:13 UTC, apognu commented
I'll see what happens with #15. If it gets merged, I'll add mocked tests related to this PR as well.

2023-11-01 22:31 UTC, gierens commented
Alright, #15 is merged, thanks again! And I took care of the minor merge conflict with the main branch. You should be good to go! :)

2023-11-02 05:20 UTC, apognu commented
Oh I got my numbers mixed, I thought this one was merged, I can rebase this properly if you want.

2023-11-02 11:15 UTC, gierens commented
If you want, got for it. But I think it's also fine the way it is. I'm not thaaaat nitpicky. At least not until the conventional commits workflow it merged haha

2023-11-04 10:44 UTC, apognu commented
Mmm, I think I messed up my rebase somehow, will that prevent the merge?

2023-11-04 17:45 UTC, gierens approved these changes
Great! Thanks for your contribution. LGTM

2023-11-04 17:45 UTC, merged